###########################################################
# Activation sweep configuration (all experiment params)
#
# This file supplies the base experiment configuration for the
# activation sweep. The sweep will iterate over the activation
# choices specified by `ks` or `ks_list`. All other parameters
# below are used as the common base config for each run.
###########################################################

# 全局随机种子，用于保证实验可重复性（整型）
seed: 123

# 运行设备："cuda"（GPU）、"mps"（Apple Metal）或 "cpu"（CPU）。
# 注意：若选择的后端不可用，程序会回退到 CPU 并打印提示。
device: "cuda"

# 激活函数的阶数 k（占位；sweep 会覆盖此项）
activation_k: 7

# MLP 宽度（隐藏层神经元数）和深度（层数）。
# depth=2 表示 1 个隐藏层（输入 → 隐藏 → 输出）。
# 是否对 ReLU^{k-1} 激活做方差归一化（保持与标准 ReLU 相同的二次矩）。
activation_normalize: true

# 方差归一化的目标二次矩，默认 0.5（对应标准 ReLU）。设为 null 可禁用缩放调节幅度。
activation_target_variance: 0.5

# 是否在每个隐藏线性层后应用 LayerNorm，以稳定更深的高阶 ReLU 网络训练。
activation_layer_norm: true

# 激活在取幂前的最大值（ReLU 输出上界），用于抑制高阶幂产生的巨梯度；设为 null 关闭。
activation_clamp_max: null

width: 256
depth: 2

# 权重裁剪范围（绝对值上限），用于数值稳定或隐式正则化。
# 如果不想裁剪可以设置为 null。
weight_clip: null

# 学习率（Adam）
lr: 1.0e-3

# 梯度裁剪阈值（L2 范数）。可在高阶激活/深网络时抑制梯度爆炸；设为 null 关闭。
grad_clip_norm: 1.0

# 训练时每次迭代采样的批大小（min(batch_size, samples) 会被使用）。
batch_size: 1024

# 总训练步数（可由命令行 --steps 覆盖）
steps: 7000

# 用于近似积分/训练的球面采样点总数（全局样本集大小）。
samples: 20000

# 近似的阶数 s_order：控制损失中是否包含 Laplace 等二阶信息。
s_order: 0
value_weight: 1.0
grad_weight: 0.0
laplace_weight: 0.0

# 任务类型："approx" 或 "poisson"
task: "approx"

# 指定实验几何体："sphere" 或 "torus"
geometry: "sphere"

# 当 geometry 为 "torus" 时的目标函数（解析 Laplace）
# 目标函数选择（可在命令行通过 --target 覆盖，例如 --target sph_l_3）：
# - "linear"       : 线性目标 f(x)=a·x（l=1 谐波）
# - "quad"         : 二次去迹目标（l=2 谐波成分）
# - "l1_plus_l2"   : 线性 + 二次去迹 的组合
# - "sph_l_N"      : 指定 zonal 球谐 Y_N^0（例如 "sph_l_3" 表示 l=3），适合需要至少 3 阶球谐的场景
# - "torus_fourier": 环面上的 Fourier 模式（u,v）=(mode_u, mode_v) 的线性组合

target: "sph_l_3"

# 环面几何参数与目标 Fourier 模式
torus_R: 2
torus_r: 1
torus_mode_u: 3
torus_mode_v: 2  
torus_amp_u: 0.15
torus_amp_v: 0.15

# 输入仍嵌入在 R^3 中
ambient_dim: 3

# 日志保存间隔（训练步数）
log_interval: 100

# 是否在训练过程中保存当前最优模型 (基于记录的训练损失最小值)
# 在某些调试/快速实验中可以设置为 false 以减少磁盘写入
save_best: true

# Activation sweep specification (choose ONE of the following)
# - ks: "2-8"      (range string, closed interval)
# - ks_list: [2,3,5] (explicit list)
ks: [2,3,4,5,6,7,8]
# ks_list: [2,3,4,5]

# Evaluation settings used after each run (samples for eval)
eval_samples: 2048

# Number of repeats per k (optional - defaults to 1)
repeats: 5

############################################################
